meta:
  id: dpx
  title: SMPTE Digital Picture Exchange image header
doc: |
  SMPTE Digital Picture Exchange (DPX) image header.

  The first four bytes are either "SDPX" (most-significant byte first)
  or "XPDS" (least-significant byte first).  The selected byte order is
  applied to the bounded 768-byte file-information header and 640-byte
  image-information header.  The latter starts at byte 768 and carries
  the image dimensions at bytes 772 and 776.

  Proven against ffprobe 6.1.1-3ubuntu5 on a deterministic 32x24 RGB24
  sample generated by FFmpeg's image2 muxer and DPX encoder.  Gallery
  status: **net-new**.  Independence regime: **self-generated** (FFmpeg
  encoded and adjudicates the sample, independently of this spec).

seq:
  - id: magic
    type: u4be
    valid:
      any-of: [0x53445058, 0x58504453]
    doc: |
      Raw first four bytes read as big-endian: 0x53445058 is "SDPX"
      (big-endian file), while 0x58504453 is "XPDS" (little-endian file).
  - id: body
    type: dpx_body
    doc: Header body parsed in the byte order selected by the magic.

instances:
  codec_label:
    value: '"dpx"'
    doc: ffprobe codec name for a DPX image.

types:
  dpx_body:
    meta:
      endian:
        switch-on: _root.magic
        cases:
          0x53445058: be
          0x58504453: le
    seq:
      - id: file_information
        size: 764
        type: file_information_after_magic
        doc: |
          Bytes 4 through 767 of the fixed 768-byte file-information
          header; the four-byte magic was consumed by the root type.
      - id: image_information
        size: 640
        type: image_information_header
        doc: Fixed image-information header at absolute byte offset 768.

    types:
      file_information_after_magic:
        seq:
          - id: image_data_offset
            type: u4
            valid:
              min: 1664
            doc: Absolute byte offset to the image data.
          - id: version
            size: 4
            valid:
              any-of:
                - '[0x56, 0x31, 0x2e, 0x30]'
                - '[0x56, 0x32, 0x2e, 0x30]'
            doc: DPX header version prefix, "V1.0" or "V2.0".
          - id: version_padding
            size: 4
            doc: Remaining bytes in the eight-byte version field.
          - id: file_size
            type: u4
            valid:
              min: image_data_offset
            doc: Total file size in bytes, including header and image data.
          - id: ditto_key
            type: u4
            valid:
              any-of: [0, 1, 0xffffffff]
            doc: |
              Zero repeats the preceding frame header, one is a new header,
              and 0xFFFFFFFF is the undefined value for this non-core field.
          - id: generic_header_length
            type: u4
            valid: 1664
            doc: Size of the three fixed generic headers in bytes.
          - id: industry_header_length
            type: u4
            doc: Size of the optional industry-specific header in bytes.
          - id: user_defined_header_length
            type: u4
            doc: Size of the optional user-defined header in bytes.
          - id: image_filename
            size: 100
          - id: creation_datetime
            size: 24
          - id: creator
            size: 100
          - id: project_name
            size: 200
          - id: right_to_use_or_copyright
            size: 200
          - id: encryption_key
            type: u4
            doc: 0xFFFFFFFF denotes unencrypted image data.
          - id: reserved
            size: 104
            doc: Reserved tail that completes the file-information header.

      image_information_header:
        seq:
          - id: orientation
            type: u2
            valid:
              max: 7
            doc: Image orientation code (0 through 7).
          - id: number_of_elements
            type: u2
            valid:
              min: 1
              max: 8
            doc: Number of active image elements.
          - id: pixels_per_line
            type: u4
            valid:
              min: 1
            doc: Frame width in pixels, at absolute byte offset 772.
          - id: lines_per_image_element
            type: u4
            valid:
              min: 1
            doc: Frame height in lines, at absolute byte offset 776.
          - id: first_image_element
            size: 72
            type: image_element
            doc: Complete fixed data structure for the first image element.
          - id: remaining_image_elements
            size: 504
            doc: Seven bounded 72-byte image-element slots (elements 2-8).
          - id: reserved
            size: 52
            doc: Reserved tail completing the 640-byte image-information header.

      image_element:
        seq:
          - id: data_sign
            type: u4
            valid:
              any-of: [0, 1]
            doc: Zero for unsigned data; one for signed data.
          - id: reference_low_data_code
            type: u4
          - id: reference_low_quantity_bits
            type: u4
            doc: Raw IEEE-754 bits, preserving the standard's undefined value.
          - id: reference_high_data_code
            type: u4
          - id: reference_high_quantity_bits
            type: u4
            doc: Raw IEEE-754 bits, preserving the standard's undefined value.
          - id: descriptor
            type: u1
          - id: transfer_characteristic
            type: u1
          - id: colorimetric_specification
            type: u1
          - id: bit_depth
            type: u1
            valid:
              any-of: [1, 8, 10, 12, 16, 32, 64]
          - id: packing
            type: u2
            valid:
              max: 2
          - id: encoding
            type: u2
            valid:
              max: 1
          - id: data_offset
            type: u4
            valid:
              min: 1664
            doc: Absolute byte offset to this element's image data.
          - id: end_of_line_padding
            type: u4
          - id: end_of_image_padding
            type: u4
          - id: description
            size: 32
